### ISSUE TITLE
CocoaPods installation fails (unable to find a specification)

### ISSUE THREAD

**Issue by andriichernenko** [onmyway133/MainThreadGuard#2]
Adding the following line to `Podfile` does not work:

```
pod 'MainThreadGuard'
```

The error is

`[!] Unable to find a specification for 'MainThreadGuard'`

**Comment by onmyway133** [comment]
@deville sorry, I can't make a Cocoapods because this idea is from https://gist.github.com/steipete/5664345, I make it Cocoapods compatible so that it helps me, and some others

In the mean time, you can point to my Github

`pod MainThreadGuard, :git => https://github.com/onmyway133/MainThreadGuard`
